[project]
name = 'Decentralized-Public-Health-Longevity-Governance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ethical-framework]
path = 'contracts/ethical-framework.clar'
clarity_version = 2
epoch = 2.5

[contracts.longevity-policy]
path = 'contracts/longevity-policy.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
